### ISSUE TITLE
Option to suppress REAPER output

### ISSUE THREAD

**Issue by terriyu** [r9y9/pyreaper#2]
Hi,

Is there any method I can use to suppress printing statements like
```
Residual symmetry: P:2468.209473  N:1539.423462  MEAN:0.045802
Inverting signal
```
when I run `pyreaper.reaper()`?

I tried using a context like this:

```python
class DummyFile(object):
    def write(self, x): pass

@contextlib.contextmanager
def suppress_print():
    save_stdout = sys.stdout
    save_stderr = sys.stderr
    sys.stdout = DummyFile()
    sys.stderr = DummyFile()
    yield
    sys.stdout = save_stdout
    sys.stderr = save_stderr
```
but it doesn't work.  I guess since cython is used, the output is going through somewhere else besides stdout.

**Comment by terriyu** [comment]
I found this [post](https://eli.thegreenplace.net/2015/redirecting-all-kinds-of-stdout-in-python/) which explains that C level streams need special handling.  Unfortunately, I haven't gotten it to work in all cases that I need.

**Comment by r9y9** [comment]
The easiest way I can think of is to remove `fprintf` lines in REAPER (https://github.com/google/REAPER/blob/b171300c077be1098cc2fb5d440ee244bd5a4c39/epoch_tracker/epoch_tracker.cc#L766-L769) itself and re-build cython module.

**Comment by terriyu** [comment]
Thanks for that idea.  Can I fork your repo and try removing the lines?

**Comment by r9y9** [comment]
Sure!

**Comment by terriyu** [comment]
It worked, thank you!
